version: '3'

services:
  silo:
    image: conreign-silo
    build:
      context: ./../Conreign.Server.Host.Console.Silo
      dockerfile: Dockerfile
  api:
    image: conreign-api
    build:
      context: ./../Conreign.Server.Host.Console.Api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
